version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/auth-ext"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    assignees:
      - "NunesMig"
    commit-message:
      prefix: "pip"
